spring.application.name=demo
server.port=8081
# Enable the shutdown endpoint (disabled by default)

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
spring.main.web-application-type=servlet
management.endpoints.web.exposure.include=shutdown
management.endpoint.shutdown.access=unrestricted
#server.servlet.session.timeout=10m
